name: 🐛 Bug Report
description: Signaler un bug ou un problème
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug ! Cela nous aide à améliorer la plateforme CSS.

  - type: dropdown
    id: component
    attributes:
      label: Composant affecté
      description: Quel composant est concerné ?
      options:
        - Backend (Laravel)
        - Frontend (React)
        - Mobile (React Native)
        - Base de données
        - API
        - CI/CD
        - Documentation
        - Autre
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Décrivez clairement le problème rencontré
      placeholder: Quand je clique sur..., il se passe...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment peut-on reproduire ce bug ?
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer ?
      placeholder: Je m'attendais à...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il réellement ?
      placeholder: Actuellement, il se passe...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: Informations sur votre environnement
      placeholder: |
        - OS: [ex: macOS 14, Windows 11, Ubuntu 22.04]
        - Navigateur: [ex: Chrome 120, Safari 17]
        - Version PHP: [ex: 8.3]
        - Version Node: [ex: 20.10]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Erreurs
      description: Collez les logs ou messages d'erreur
      render: shell
      placeholder: |
        Error message here...
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Ajoutez des captures d'écran si pertinent
      placeholder: Glissez-déposez les images ici
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: J'ai vérifié qu'il n'y a pas d'issue similaire
          required: true
        - label: J'ai testé avec la dernière version
          required: false
