<?php

namespace Database\Seeders;

use App\Models\Partner;
use App\Models\PartnerCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PartnerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $restauration = PartnerCategory::where('slug', 'restauration')->first();
        $hotellerie = PartnerCategory::where('slug', 'hotellerie-tourisme')->first();
        $sport = PartnerCategory::where('slug', 'sport-bien-etre')->first();
        $shopping = PartnerCategory::where('slug', 'shopping')->first();
        $services = PartnerCategory::where('slug', 'services')->first();
        $loisirs = PartnerCategory::where('slug', 'loisirs')->first();
        $education = PartnerCategory::where('slug', 'education')->first();
        $sante = PartnerCategory::where('slug', 'sante')->first();

        $partners = [
            // Restauration (10 partenaires)
            [
                'category_id' => $restauration->id,
                'name' => 'Restaurant Le Medina',
                'slug' => 'restaurant-le-medina',
                'description' => 'Restaurant de cuisine tunisienne traditionnelle au coeur de la médina de Sfax. Spécialités : couscous, tajines, poissons grillés. Ambiance authentique avec vue sur la vieille ville.',
                'address' => 'Avenue Habib Bourguiba, Médina',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 221 345',
                'email' => 'contact@lemedina-sfax.tn',
                'website' => 'https://lemedina-sfax.tn',
                'latitude' => 34.7406 + (rand(-50, 50) / 10000),
                'longitude' => 10.7603 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '12:00-15:00, 19:00-23:00',
                    'mardi' => '12:00-15:00, 19:00-23:00',
                    'mercredi' => '12:00-15:00, 19:00-23:00',
                    'jeudi' => '12:00-15:00, 19:00-23:00',
                    'vendredi' => '12:00-15:00, 19:00-00:00',
                    'samedi' => '12:00-15:00, 19:00-00:00',
                    'dimanche' => '12:00-15:00, 19:00-23:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 8,
                'status' => 'active',
                'featured_order' => 1,
                'rating_average' => 4.6,
                'reviews_count' => 127,
                'views_count' => 1234,
            ],
            [
                'category_id' => $restauration->id,
                'name' => 'Pizza Hut Sfax',
                'slug' => 'pizza-hut-sfax',
                'description' => 'La célèbre chaîne de pizzas internationale. Large choix de pizzas, pâtes et desserts. Service rapide et livraison à domicile disponible.',
                'address' => 'Avenue Majida Boulila',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 400 500',
                'email' => 'sfax@pizzahut.tn',
                'website' => 'https://pizzahut.tn',
                'latitude' => 34.7445 + (rand(-50, 50) / 10000),
                'longitude' => 10.7580 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '11:00-23:00',
                    'mardi' => '11:00-23:00',
                    'mercredi' => '11:00-23:00',
                    'jeudi' => '11:00-23:00',
                    'vendredi' => '11:00-00:00',
                    'samedi' => '11:00-00:00',
                    'dimanche' => '11:00-23:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.2,
                'reviews_count' => 89,
                'views_count' => 856,
            ],
            [
                'category_id' => $restauration->id,
                'name' => 'Café des Délices',
                'slug' => 'cafe-des-delices',
                'description' => 'Café traditionnel avec vue sur la mer. Spécialités de cafés tunisiens, pâtisseries orientales et glaces artisanales. Idéal pour une pause détente.',
                'address' => 'Avenue Hedi Chaker',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 298 765',
                'email' => 'info@cafedelices.tn',
                'latitude' => 34.7398 + (rand(-50, 50) / 10000),
                'longitude' => 10.7625 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 8,
                'reduction_value_socios' => 15,
                'opening_hours' => json_encode([
                    'lundi' => '07:00-22:00',
                    'mardi' => '07:00-22:00',
                    'mercredi' => '07:00-22:00',
                    'jeudi' => '07:00-22:00',
                    'vendredi' => '07:00-23:00',
                    'samedi' => '07:00-23:00',
                    'dimanche' => '08:00-22:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 6,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.4,
                'reviews_count' => 156,
                'views_count' => 987,
            ],
            [
                'category_id' => $restauration->id,
                'name' => 'Restaurant Le Corail',
                'slug' => 'restaurant-le-corail',
                'description' => 'Restaurant spécialisé en fruits de mer et poissons frais. Vue panoramique sur le port de Sfax. Cadre élégant pour repas d\'affaires ou en famille.',
                'address' => 'Route de la Corniche',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 227 890',
                'email' => 'reservations@lecorail.tn',
                'website' => 'https://lecorail-sfax.tn',
                'latitude' => 34.7390 + (rand(-50, 50) / 10000),
                'longitude' => 10.7670 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 15,
                'reduction_value_socios' => 25,
                'opening_hours' => json_encode([
                    'lundi' => 'Fermé',
                    'mardi' => '12:00-15:00, 19:00-23:00',
                    'mercredi' => '12:00-15:00, 19:00-23:00',
                    'jeudi' => '12:00-15:00, 19:00-23:00',
                    'vendredi' => '12:00-15:00, 19:00-00:00',
                    'samedi' => '12:00-15:00, 19:00-00:00',
                    'dimanche' => '12:00-15:00, 19:00-23:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 12,
                'status' => 'active',
                'featured_order' => 2,
                'rating_average' => 4.7,
                'reviews_count' => 234,
                'views_count' => 1567,
            ],
            [
                'category_id' => $restauration->id,
                'name' => 'Dar Chraka',
                'slug' => 'dar-chraka',
                'description' => 'Restaurant gastronomique dans une demeure traditionnelle restaurée. Cuisine tunisienne raffinée avec une touche moderne. Ambiance chaleureuse et authentique.',
                'address' => 'Rue de la Kasbah, Médina',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 223 456',
                'email' => 'contact@darchronaka.tn',
                'latitude' => 34.7415 + (rand(-50, 50) / 10000),
                'longitude' => 10.7595 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 18,
                'opening_hours' => json_encode([
                    'lundi' => '12:00-15:00, 19:00-22:00',
                    'mardi' => '12:00-15:00, 19:00-22:00',
                    'mercredi' => '12:00-15:00, 19:00-22:00',
                    'jeudi' => '12:00-15:00, 19:00-22:00',
                    'vendredi' => '12:00-15:00, 19:00-23:00',
                    'samedi' => '12:00-15:00, 19:00-23:00',
                    'dimanche' => '12:00-15:00, 19:00-22:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 9,
                'status' => 'active',
                'featured_order' => 3,
                'rating_average' => 4.8,
                'reviews_count' => 178,
                'views_count' => 1423,
            ],
            [
                'category_id' => $restauration->id,
                'name' => 'Fast Food El Hana',
                'slug' => 'fast-food-el-hana',
                'description' => 'Fast-food tunisien proposant des sandwichs, chapatis, tacos et plats rapides. Service rapide et prix abordables.',
                'address' => 'Avenue Hedi Chaker',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 245 678',
                'latitude' => 34.7428 + (rand(-50, 50) / 10000),
                'longitude' => 10.7612 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 15,
                'opening_hours' => json_encode([
                    'lundi' => '10:00-23:00',
                    'mardi' => '10:00-23:00',
                    'mercredi' => '10:00-23:00',
                    'jeudi' => '10:00-23:00',
                    'vendredi' => '10:00-00:00',
                    'samedi' => '10:00-00:00',
                    'dimanche' => '10:00-23:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 7,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.0,
                'reviews_count' => 67,
                'views_count' => 543,
            ],

            // Hôtellerie & Tourisme (6 partenaires)
            [
                'category_id' => $hotellerie->id,
                'name' => 'Novotel Sfax Centre',
                'slug' => 'novotel-sfax-centre',
                'description' => 'Hôtel 4 étoiles au centre-ville de Sfax. Chambres modernes, restaurant, piscine, salle de fitness. Idéal pour séjours d\'affaires et touristiques.',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 225 700',
                'email' => 'h3183@accor.com',
                'website' => 'https://novotel.com/sfax',
                'latitude' => 34.7420 + (rand(-50, 50) / 10000),
                'longitude' => 10.7598 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 15,
                'reduction_value_socios' => 25,
                'opening_hours' => json_encode([
                    'lundi' => '24h/24',
                    'mardi' => '24h/24',
                    'mercredi' => '24h/24',
                    'jeudi' => '24h/24',
                    'vendredi' => '24h/24',
                    'samedi' => '24h/24',
                    'dimanche' => '24h/24',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 4,
                'rating_average' => 4.5,
                'reviews_count' => 312,
                'views_count' => 2134,
            ],
            [
                'category_id' => $hotellerie->id,
                'name' => 'Hotel Les Oliviers',
                'slug' => 'hotel-les-oliviers',
                'description' => 'Hôtel 3 étoiles familial avec jardin. Service personnalisé, petit-déjeuner inclus. Parking gratuit disponible.',
                'address' => 'Route de Tunis, Km 2',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 241 800',
                'email' => 'contact@lesoliviers-sfax.tn',
                'latitude' => 34.7502 + (rand(-50, 50) / 10000),
                'longitude' => 10.7545 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '24h/24',
                    'mardi' => '24h/24',
                    'mercredi' => '24h/24',
                    'jeudi' => '24h/24',
                    'vendredi' => '24h/24',
                    'samedi' => '24h/24',
                    'dimanche' => '24h/24',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 8,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.1,
                'reviews_count' => 145,
                'views_count' => 976,
            ],
            [
                'category_id' => $hotellerie->id,
                'name' => 'La Maison Blanche',
                'slug' => 'la-maison-blanche',
                'description' => 'Maison d\'hôtes de charme dans la médina. Architecture traditionnelle, décoration soignée. Petit-déjeuner sur terrasse avec vue.',
                'address' => 'Rue Mongi Slim, Médina',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 229 345',
                'email' => 'info@maisonblanche-sfax.tn',
                'website' => 'https://maisonblanche-sfax.tn',
                'latitude' => 34.7410 + (rand(-50, 50) / 10000),
                'longitude' => 10.7600 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 18,
                'opening_hours' => json_encode([
                    'lundi' => '24h/24',
                    'mardi' => '24h/24',
                    'mercredi' => '24h/24',
                    'jeudi' => '24h/24',
                    'vendredi' => '24h/24',
                    'samedi' => '24h/24',
                    'dimanche' => '24h/24',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 9,
                'status' => 'active',
                'featured_order' => 5,
                'rating_average' => 4.7,
                'reviews_count' => 98,
                'views_count' => 789,
            ],
            [
                'category_id' => $hotellerie->id,
                'name' => 'Agence Tunisie Voyages',
                'slug' => 'agence-tunisie-voyages',
                'description' => 'Agence de voyage proposant circuits touristiques, réservations d\'hôtels, billets d\'avion. Service personnalisé et conseils experts.',
                'address' => 'Avenue Majida Boulila',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 243 567',
                'email' => 'sfax@tunisievoyages.tn',
                'website' => 'https://tunisievoyages.tn',
                'latitude' => 34.7440 + (rand(-50, 50) / 10000),
                'longitude' => 10.7575 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 8,
                'reduction_value_socios' => 12,
                'opening_hours' => json_encode([
                    'lundi' => '08:30-12:30, 14:00-18:00',
                    'mardi' => '08:30-12:30, 14:00-18:00',
                    'mercredi' => '08:30-12:30, 14:00-18:00',
                    'jeudi' => '08:30-12:30, 14:00-18:00',
                    'vendredi' => '08:30-12:30, 14:00-18:00',
                    'samedi' => '09:00-13:00',
                    'dimanche' => 'Fermé',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => false,
                'commission_percentage' => 7,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.3,
                'reviews_count' => 76,
                'views_count' => 654,
            ],

            // Sport & Bien-être (8 partenaires)
            [
                'category_id' => $sport->id,
                'name' => 'Fitness Zone Sfax',
                'slug' => 'fitness-zone-sfax',
                'description' => 'Salle de sport équipée avec machines dernière génération, espace cardio, musculation, cours collectifs. Coachs diplômés disponibles.',
                'address' => 'Avenue Hedi Chaker',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 456 789',
                'email' => 'info@fitnesszone-sfax.tn',
                'latitude' => 34.7425 + (rand(-50, 50) / 10000),
                'longitude' => 10.7615 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 15,
                'reduction_value_socios' => 25,
                'opening_hours' => json_encode([
                    'lundi' => '06:00-22:00',
                    'mardi' => '06:00-22:00',
                    'mercredi' => '06:00-22:00',
                    'jeudi' => '06:00-22:00',
                    'vendredi' => '06:00-22:00',
                    'samedi' => '08:00-20:00',
                    'dimanche' => '08:00-20:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 6,
                'rating_average' => 4.6,
                'reviews_count' => 189,
                'views_count' => 1345,
            ],
            [
                'category_id' => $sport->id,
                'name' => 'Club Sportif Gym',
                'slug' => 'club-sportif-gym',
                'description' => 'Salle de musculation et fitness. Équipements modernes, vestiaires spacieux, sauna. Abonnements flexibles.',
                'address' => 'Rue Ali Bach Hamba',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 467 890',
                'latitude' => 34.7395 + (rand(-50, 50) / 10000),
                'longitude' => 10.7588 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '07:00-21:00',
                    'mardi' => '07:00-21:00',
                    'mercredi' => '07:00-21:00',
                    'jeudi' => '07:00-21:00',
                    'vendredi' => '07:00-21:00',
                    'samedi' => '09:00-19:00',
                    'dimanche' => '09:00-19:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 8,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.3,
                'reviews_count' => 134,
                'views_count' => 876,
            ],
            [
                'category_id' => $sport->id,
                'name' => 'Spa Wellness Center',
                'slug' => 'spa-wellness-center',
                'description' => 'Centre de bien-être proposant massages, soins du visage, hammam traditionnel. Ambiance relaxante et professionnels qualifiés.',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 478 901',
                'email' => 'contact@spawellness-sfax.tn',
                'latitude' => 34.7418 + (rand(-50, 50) / 10000),
                'longitude' => 10.7602 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 15,
                'reduction_value_socios' => 25,
                'opening_hours' => json_encode([
                    'lundi' => '09:00-20:00',
                    'mardi' => '09:00-20:00',
                    'mercredi' => '09:00-20:00',
                    'jeudi' => '09:00-20:00',
                    'vendredi' => '09:00-20:00',
                    'samedi' => '10:00-18:00',
                    'dimanche' => 'Fermé',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 12,
                'status' => 'active',
                'featured_order' => 7,
                'rating_average' => 4.8,
                'reviews_count' => 215,
                'views_count' => 1678,
            ],
            [
                'category_id' => $sport->id,
                'name' => 'Boutique Sport Plus',
                'slug' => 'boutique-sport-plus',
                'description' => 'Magasin d\'équipements sportifs. Large gamme : chaussures, vêtements, accessoires pour tous sports. Marques internationales et locales.',
                'address' => 'Avenue Majida Boulila',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 489 012',
                'email' => 'info@sportplus.tn',
                'latitude' => 34.7442 + (rand(-50, 50) / 10000),
                'longitude' => 10.7578 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 15,
                'opening_hours' => json_encode([
                    'lundi' => '09:00-19:00',
                    'mardi' => '09:00-19:00',
                    'mercredi' => '09:00-19:00',
                    'jeudi' => '09:00-19:00',
                    'vendredi' => '09:00-19:00',
                    'samedi' => '09:00-20:00',
                    'dimanche' => '10:00-18:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 9,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.4,
                'reviews_count' => 112,
                'views_count' => 945,
            ],
            [
                'category_id' => $sport->id,
                'name' => 'Piscine Olympique Sfax',
                'slug' => 'piscine-olympique-sfax',
                'description' => 'Piscine olympique couverte. Cours de natation pour tous niveaux, aquagym. Vestiaires et douches inclus.',
                'address' => 'Route de l\'Aéroport',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 490 123',
                'latitude' => 34.7355 + (rand(-50, 50) / 10000),
                'longitude' => 10.7520 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 18,
                'opening_hours' => json_encode([
                    'lundi' => '07:00-20:00',
                    'mardi' => '07:00-20:00',
                    'mercredi' => '07:00-20:00',
                    'jeudi' => '07:00-20:00',
                    'vendredi' => '07:00-20:00',
                    'samedi' => '08:00-18:00',
                    'dimanche' => '08:00-18:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 7,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.2,
                'reviews_count' => 87,
                'views_count' => 723,
            ],

            // Shopping (8 partenaires)
            [
                'category_id' => $shopping->id,
                'name' => 'Carrefour Sfax',
                'slug' => 'carrefour-sfax',
                'description' => 'Hypermarché Carrefour avec large gamme de produits alimentaires, électronique, vêtements, maison. Parking gratuit.',
                'address' => 'Avenue Majida Boulila',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 500 600',
                'email' => 'sfax@carrefour.tn',
                'website' => 'https://carrefour.tn',
                'latitude' => 34.7448 + (rand(-50, 50) / 10000),
                'longitude' => 10.7572 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 5,
                'reduction_value_socios' => 10,
                'opening_hours' => json_encode([
                    'lundi' => '08:30-21:00',
                    'mardi' => '08:30-21:00',
                    'mercredi' => '08:30-21:00',
                    'jeudi' => '08:30-21:00',
                    'vendredi' => '08:30-21:30',
                    'samedi' => '08:30-21:30',
                    'dimanche' => '08:30-21:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 5,
                'status' => 'active',
                'featured_order' => 8,
                'rating_average' => 4.3,
                'reviews_count' => 567,
                'views_count' => 3456,
            ],
            [
                'category_id' => $shopping->id,
                'name' => 'Azur City Mall',
                'slug' => 'azur-city-mall',
                'description' => 'Centre commercial moderne avec boutiques de mode, restaurants, cinéma, espace jeux pour enfants. Climatisé.',
                'address' => 'Route de Tunis',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 510 700',
                'email' => 'info@azurcity.tn',
                'website' => 'https://azurcity-sfax.tn',
                'latitude' => 34.7520 + (rand(-50, 50) / 10000),
                'longitude' => 10.7540 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 8,
                'reduction_value_socios' => 12,
                'opening_hours' => json_encode([
                    'lundi' => '10:00-22:00',
                    'mardi' => '10:00-22:00',
                    'mercredi' => '10:00-22:00',
                    'jeudi' => '10:00-22:00',
                    'vendredi' => '10:00-23:00',
                    'samedi' => '10:00-23:00',
                    'dimanche' => '10:00-22:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 8,
                'status' => 'active',
                'featured_order' => 9,
                'rating_average' => 4.5,
                'reviews_count' => 423,
                'views_count' => 2789,
            ],
            [
                'category_id' => $shopping->id,
                'name' => 'Electroplanet Sfax',
                'slug' => 'electroplanet-sfax',
                'description' => 'Magasin d\'électronique et électroménager. TV, smartphones, ordinateurs, appareils ménagers. Garantie et service après-vente.',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 520 800',
                'email' => 'sfax@electroplanet.tn',
                'website' => 'https://electroplanet.tn',
                'latitude' => 34.7422 + (rand(-50, 50) / 10000),
                'longitude' => 10.7600 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 15,
                'opening_hours' => json_encode([
                    'lundi' => '09:00-19:00',
                    'mardi' => '09:00-19:00',
                    'mercredi' => '09:00-19:00',
                    'jeudi' => '09:00-19:00',
                    'vendredi' => '09:00-19:00',
                    'samedi' => '09:00-20:00',
                    'dimanche' => '10:00-18:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 7,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.2,
                'reviews_count' => 198,
                'views_count' => 1567,
            ],
            [
                'category_id' => $shopping->id,
                'name' => 'Fashion Store Sfax',
                'slug' => 'fashion-store-sfax',
                'description' => 'Boutique de mode homme, femme et enfant. Dernières tendances, marques internationales. Collections renouvelées régulièrement.',
                'address' => 'Avenue Majida Boulila',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 530 900',
                'email' => 'contact@fashionstore.tn',
                'latitude' => 34.7445 + (rand(-50, 50) / 10000),
                'longitude' => 10.7576 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '09:30-19:30',
                    'mardi' => '09:30-19:30',
                    'mercredi' => '09:30-19:30',
                    'jeudi' => '09:30-19:30',
                    'vendredi' => '09:30-20:00',
                    'samedi' => '09:30-20:00',
                    'dimanche' => '10:00-18:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.4,
                'reviews_count' => 176,
                'views_count' => 1234,
            ],

            // Services (8 partenaires)
            [
                'category_id' => $services->id,
                'name' => 'Salon de Coiffure Elite',
                'slug' => 'salon-coiffure-elite',
                'description' => 'Salon de coiffure mixte. Coupes modernes, colorations, soins capillaires. Équipe de coiffeurs expérimentés.',
                'address' => 'Rue Ali Bach Hamba',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 540 111',
                'latitude' => 34.7400 + (rand(-50, 50) / 10000),
                'longitude' => 10.7590 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 15,
                'reduction_value_socios' => 25,
                'opening_hours' => json_encode([
                    'lundi' => '09:00-19:00',
                    'mardi' => '09:00-19:00',
                    'mercredi' => '09:00-19:00',
                    'jeudi' => '09:00-19:00',
                    'vendredi' => '09:00-19:00',
                    'samedi' => '09:00-20:00',
                    'dimanche' => 'Fermé',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.6,
                'reviews_count' => 234,
                'views_count' => 1456,
            ],
            [
                'category_id' => $services->id,
                'name' => 'Garage Auto Service',
                'slug' => 'garage-auto-service',
                'description' => 'Garage automobile complet. Réparation, entretien, diagnostic électronique. Toutes marques acceptées.',
                'address' => 'Route de Gabes',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 550 222',
                'email' => 'contact@autoservice-sfax.tn',
                'latitude' => 34.7320 + (rand(-50, 50) / 10000),
                'longitude' => 10.7650 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 15,
                'opening_hours' => json_encode([
                    'lundi' => '08:00-18:00',
                    'mardi' => '08:00-18:00',
                    'mercredi' => '08:00-18:00',
                    'jeudi' => '08:00-18:00',
                    'vendredi' => '08:00-18:00',
                    'samedi' => '08:00-13:00',
                    'dimanche' => 'Fermé',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 8,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.3,
                'reviews_count' => 156,
                'views_count' => 987,
            ],
            [
                'category_id' => $services->id,
                'name' => 'Pressing Clean Service',
                'slug' => 'pressing-clean-service',
                'description' => 'Pressing et nettoyage à sec. Service rapide, traitement des taches difficiles. Repassage soigné.',
                'address' => 'Avenue Hedi Chaker',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 560 333',
                'latitude' => 34.7430 + (rand(-50, 50) / 10000),
                'longitude' => 10.7610 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '08:00-19:00',
                    'mardi' => '08:00-19:00',
                    'mercredi' => '08:00-19:00',
                    'jeudi' => '08:00-19:00',
                    'vendredi' => '08:00-19:00',
                    'samedi' => '08:00-18:00',
                    'dimanche' => 'Fermé',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 9,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.5,
                'reviews_count' => 189,
                'views_count' => 1123,
            ],

            // Loisirs (5 partenaires)
            [
                'category_id' => $loisirs->id,
                'name' => 'Cinéma Pathé Sfax',
                'slug' => 'cinema-pathe-sfax',
                'description' => 'Cinéma multiplex moderne. 8 salles, son Dolby Atmos, sièges confortables. Films en VF et VO.',
                'address' => 'Azur City Mall',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 570 444',
                'email' => 'sfax@pathe.tn',
                'website' => 'https://pathe.tn/sfax',
                'latitude' => 34.7520 + (rand(-50, 50) / 10000),
                'longitude' => 10.7540 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 15,
                'reduction_value_socios' => 25,
                'opening_hours' => json_encode([
                    'lundi' => '14:00-00:00',
                    'mardi' => '14:00-00:00',
                    'mercredi' => '14:00-00:00',
                    'jeudi' => '14:00-00:00',
                    'vendredi' => '14:00-01:00',
                    'samedi' => '14:00-01:00',
                    'dimanche' => '10:00-00:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 12,
                'status' => 'active',
                'featured_order' => 10,
                'rating_average' => 4.7,
                'reviews_count' => 389,
                'views_count' => 2456,
            ],
            [
                'category_id' => $loisirs->id,
                'name' => 'Bowling Paradise',
                'slug' => 'bowling-paradise',
                'description' => 'Centre de bowling avec 12 pistes automatisées. Bar, snack, espace jeux d\'arcade. Idéal pour sorties entre amis.',
                'address' => 'Route de Tunis',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 580 555',
                'email' => 'info@bowlingparadise.tn',
                'latitude' => 34.7515 + (rand(-50, 50) / 10000),
                'longitude' => 10.7545 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '15:00-00:00',
                    'mardi' => '15:00-00:00',
                    'mercredi' => '15:00-00:00',
                    'jeudi' => '15:00-00:00',
                    'vendredi' => '15:00-01:00',
                    'samedi' => '15:00-01:00',
                    'dimanche' => '10:00-00:00',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.4,
                'reviews_count' => 167,
                'views_count' => 1345,
            ],

            // Éducation (4 partenaires)
            [
                'category_id' => $education->id,
                'name' => 'Centre de Langues International',
                'slug' => 'centre-langues-international',
                'description' => 'Centre de formation en langues étrangères. Cours d\'anglais, français, allemand, espagnol. Tous niveaux.',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 590 666',
                'email' => 'contact@langues-international.tn',
                'website' => 'https://langues-international.tn',
                'latitude' => 34.7424 + (rand(-50, 50) / 10000),
                'longitude' => 10.7598 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 15,
                'reduction_value_socios' => 25,
                'opening_hours' => json_encode([
                    'lundi' => '09:00-20:00',
                    'mardi' => '09:00-20:00',
                    'mercredi' => '09:00-20:00',
                    'jeudi' => '09:00-20:00',
                    'vendredi' => '09:00-20:00',
                    'samedi' => '09:00-18:00',
                    'dimanche' => 'Fermé',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => false,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 11,
                'rating_average' => 4.8,
                'reviews_count' => 245,
                'views_count' => 1789,
            ],
            [
                'category_id' => $education->id,
                'name' => 'Cours de Soutien Excellence',
                'slug' => 'cours-soutien-excellence',
                'description' => 'Cours de soutien scolaire toutes matières. Primaire, collège, lycée. Professeurs qualifiés et expérimentés.',
                'address' => 'Rue Mongi Slim',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 600 777',
                'email' => 'info@excellence-sfax.tn',
                'latitude' => 34.7408 + (rand(-50, 50) / 10000),
                'longitude' => 10.7595 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 18,
                'opening_hours' => json_encode([
                    'lundi' => '14:00-20:00',
                    'mardi' => '14:00-20:00',
                    'mercredi' => '14:00-20:00',
                    'jeudi' => '14:00-20:00',
                    'vendredi' => '14:00-20:00',
                    'samedi' => '09:00-18:00',
                    'dimanche' => '09:00-13:00',
                ]),
                'is_online' => true,
                'is_geolocation_enabled' => false,
                'commission_percentage' => 9,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.6,
                'reviews_count' => 198,
                'views_count' => 1456,
            ],

            // Santé (6 partenaires)
            [
                'category_id' => $sante->id,
                'name' => 'Pharmacie Centrale',
                'slug' => 'pharmacie-centrale',
                'description' => 'Pharmacie de garde ouverte 24h/24. Large stock de médicaments, parapharmacie, conseil pharmaceutique.',
                'address' => 'Avenue Habib Bourguiba',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 610 888',
                'email' => 'contact@pharmacie-centrale-sfax.tn',
                'latitude' => 34.7416 + (rand(-50, 50) / 10000),
                'longitude' => 10.7604 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 8,
                'reduction_value_socios' => 12,
                'opening_hours' => json_encode([
                    'lundi' => '24h/24',
                    'mardi' => '24h/24',
                    'mercredi' => '24h/24',
                    'jeudi' => '24h/24',
                    'vendredi' => '24h/24',
                    'samedi' => '24h/24',
                    'dimanche' => '24h/24',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 6,
                'status' => 'active',
                'featured_order' => 12,
                'rating_average' => 4.7,
                'reviews_count' => 345,
                'views_count' => 2345,
            ],
            [
                'category_id' => $sante->id,
                'name' => 'Clinique Essalem',
                'slug' => 'clinique-essalem',
                'description' => 'Clinique privée multidisciplinaire. Urgences, consultations spécialisées, bloc opératoire moderne. Conventionnée CNAM.',
                'address' => 'Route de Tunis',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 620 999',
                'email' => 'contact@clinique-essalem.tn',
                'website' => 'https://clinique-essalem.tn',
                'latitude' => 34.7510 + (rand(-50, 50) / 10000),
                'longitude' => 10.7548 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 10,
                'reduction_value_socios' => 15,
                'opening_hours' => json_encode([
                    'lundi' => '24h/24',
                    'mardi' => '24h/24',
                    'mercredi' => '24h/24',
                    'jeudi' => '24h/24',
                    'vendredi' => '24h/24',
                    'samedi' => '24h/24',
                    'dimanche' => '24h/24',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 8,
                'status' => 'active',
                'featured_order' => 13,
                'rating_average' => 4.6,
                'reviews_count' => 289,
                'views_count' => 1987,
            ],
            [
                'category_id' => $sante->id,
                'name' => 'Laboratoire d\'Analyses Médicales',
                'slug' => 'laboratoire-analyses-medicales',
                'description' => 'Laboratoire d\'analyses médicales. Tous types d\'analyses, résultats rapides, prélèvement à domicile possible.',
                'address' => 'Avenue Majida Boulila',
                'city' => 'Sfax',
                'postal_code' => '3000',
                'phone' => '+216 74 630 100',
                'email' => 'labo@analyses-sfax.tn',
                'latitude' => 34.7438 + (rand(-50, 50) / 10000),
                'longitude' => 10.7582 + (rand(-50, 50) / 10000),
                'reduction_type' => 'percentage',
                'reduction_value_premium' => 12,
                'reduction_value_socios' => 20,
                'opening_hours' => json_encode([
                    'lundi' => '07:00-19:00',
                    'mardi' => '07:00-19:00',
                    'mercredi' => '07:00-19:00',
                    'jeudi' => '07:00-19:00',
                    'vendredi' => '07:00-19:00',
                    'samedi' => '07:00-13:00',
                    'dimanche' => 'Fermé',
                ]),
                'is_online' => false,
                'is_geolocation_enabled' => true,
                'commission_percentage' => 10,
                'status' => 'active',
                'featured_order' => 0,
                'rating_average' => 4.5,
                'reviews_count' => 213,
                'views_count' => 1654,
            ],
        ];

        foreach ($partners as $partner) {
            Partner::create($partner);
        }
    }
}
