<?php

namespace Database\Seeders;

use App\Models\PaymentMethod;
use Illuminate\Database\Seeder;

class PaymentMethodSeeder extends Seeder
{
    public function run(): void
    {
        $methods = [
            // Mobile Wallets - Portefeuilles Mobiles
            [
                'name' => 'D17',
                'code' => 'd17',
                'type' => 'mobile_wallet',
                'description' => 'Paiement via D17 - Portefeuille mobile populaire en Tunisie',
                'provider' => 'D17 Tunisie',
                'is_active' => true,
                'is_default' => true,
                'supported_currencies' => ['TND'],
                'min_amount' => 1.00,
                'max_amount' => 10000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 1.5,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Scannez le QR code avec votre application D17 pour payer',
                'display_order' => 1,
                'available_for' => ['donations', 'products', 'tickets', 'auctions', 'subscriptions'],
            ],
            [
                'name' => 'Konnect',
                'code' => 'konnect',
                'type' => 'mobile_wallet',
                'description' => 'Paiement sécurisé via Konnect',
                'provider' => 'Konnect by Ooredoo',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 1.00,
                'max_amount' => 5000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 1.2,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Payez avec votre compte Konnect',
                'display_order' => 2,
                'available_for' => ['donations', 'products', 'tickets', 'auctions', 'subscriptions'],
            ],
            [
                'name' => 'Flouci',
                'code' => 'flouci',
                'type' => 'mobile_wallet',
                'description' => 'Paiement mobile rapide avec Flouci',
                'provider' => 'Flouci',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 1.00,
                'max_amount' => 3000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 1.8,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Scannez le QR code avec Flouci',
                'display_order' => 3,
                'available_for' => ['donations', 'products', 'tickets', 'auctions'],
            ],
            [
                'name' => 'Paymee',
                'code' => 'paymee',
                'type' => 'mobile_wallet',
                'description' => 'Solution de paiement mobile tunisienne',
                'provider' => 'Paymee',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 5.00,
                'max_amount' => 5000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 2.0,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Utilisez votre application Paymee pour payer',
                'display_order' => 4,
                'available_for' => ['donations', 'products', 'tickets', 'auctions', 'subscriptions'],
            ],
            [
                'name' => 'Clictopay',
                'code' => 'clictopay',
                'type' => 'mobile_wallet',
                'description' => 'Paiement en ligne sécurisé',
                'provider' => 'Clictopay',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 1.00,
                'max_amount' => 10000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 1.5,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Payez avec Clictopay',
                'display_order' => 5,
                'available_for' => ['donations', 'products', 'tickets', 'auctions', 'subscriptions'],
            ],
            [
                'name' => 'Sobflous',
                'code' => 'sobflous',
                'type' => 'mobile_wallet',
                'description' => 'Portefeuille électronique Sobflous',
                'provider' => 'Sobflous',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 1.00,
                'max_amount' => 2000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 2.0,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Scannez le QR code avec Sobflous',
                'display_order' => 6,
                'available_for' => ['donations', 'products', 'tickets'],
            ],

            // Bank Cards - Cartes Bancaires
            [
                'name' => 'Carte Bancaire (Visa/Mastercard)',
                'code' => 'bank_card',
                'type' => 'bank_card',
                'description' => 'Paiement par carte Visa, Mastercard ou carte locale',
                'provider' => 'Banques Tunisiennes',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND', 'EUR', 'USD'],
                'min_amount' => 5.00,
                'max_amount' => 50000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 2.5,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Entrez les détails de votre carte bancaire de manière sécurisée',
                'display_order' => 7,
                'available_for' => ['donations', 'products', 'tickets', 'auctions', 'subscriptions'],
            ],
            [
                'name' => 'Sadad',
                'code' => 'sadad',
                'type' => 'bank_card',
                'description' => 'Paiement par carte Sadad',
                'provider' => 'Sadad Tunisie',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 5.00,
                'max_amount' => 10000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 2.0,
                'processing_time' => 'Instantané',
                'supports_refund' => true,
                'instructions' => 'Utilisez votre carte Sadad',
                'display_order' => 8,
                'available_for' => ['donations', 'products', 'tickets', 'auctions'],
            ],

            // Bank Transfer - Virement Bancaire
            [
                'name' => 'Virement Bancaire',
                'code' => 'bank_transfer',
                'type' => 'bank_transfer',
                'description' => 'Virement bancaire direct (RIB)',
                'provider' => 'Système Bancaire Tunisien',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 10.00,
                'max_amount' => 100000.00,
                'transaction_fee' => 0,
                'transaction_fee_percentage' => 0,
                'processing_time' => '1-3 jours ouvrables',
                'supports_refund' => true,
                'instructions' => 'Effectuez un virement vers le RIB du club. N\'oubliez pas d\'inclure votre référence de commande.',
                'display_order' => 9,
                'available_for' => ['donations', 'products', 'subscriptions'],
            ],

            // Cash on Delivery
            [
                'name' => 'Paiement à la Livraison',
                'code' => 'cash_on_delivery',
                'type' => 'cash',
                'description' => 'Payez en espèces à la réception',
                'provider' => 'Livreurs CSS',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND'],
                'min_amount' => 5.00,
                'max_amount' => 1000.00,
                'transaction_fee' => 3.00,
                'transaction_fee_percentage' => 0,
                'processing_time' => 'À la livraison',
                'supports_refund' => false,
                'instructions' => 'Préparez le montant exact pour le livreur',
                'display_order' => 10,
                'available_for' => ['products'],
            ],

            // International - Transferts Internationaux
            [
                'name' => 'Western Union',
                'code' => 'western_union',
                'type' => 'international',
                'description' => 'Transfert international via Western Union',
                'provider' => 'Western Union',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND', 'EUR', 'USD'],
                'min_amount' => 50.00,
                'max_amount' => 50000.00,
                'transaction_fee' => 15.00,
                'transaction_fee_percentage' => 3.0,
                'processing_time' => '1-2 heures',
                'supports_refund' => false,
                'instructions' => 'Effectuez un transfert Western Union. Envoyez-nous le MTCN.',
                'display_order' => 11,
                'available_for' => ['donations', 'products', 'subscriptions'],
            ],
            [
                'name' => 'MoneyGram',
                'code' => 'moneygram',
                'type' => 'international',
                'description' => 'Transfert international via MoneyGram',
                'provider' => 'MoneyGram',
                'is_active' => true,
                'is_default' => false,
                'supported_currencies' => ['TND', 'EUR', 'USD'],
                'min_amount' => 50.00,
                'max_amount' => 50000.00,
                'transaction_fee' => 15.00,
                'transaction_fee_percentage' => 3.0,
                'processing_time' => '1-2 heures',
                'supports_refund' => false,
                'instructions' => 'Effectuez un transfert MoneyGram. Envoyez-nous la référence.',
                'display_order' => 12,
                'available_for' => ['donations', 'products', 'subscriptions'],
            ],
        ];

        foreach ($methods as $method) {
            PaymentMethod::create($method);
        }

        $this->command->info('12 méthodes de paiement tunisiennes créées avec succès');
    }
}
