<?php

namespace Database\Seeders;

use App\Models\Player;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PlayerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $players = [
            // Gardiens de but (3)
            [
                'first_name' => 'Aymen',
                'last_name' => 'Dahmen',
                'position' => 'GK',
                'jersey_number' => 16,
                'nationality' => 'Tunisie',
                'birth_date' => '1997-01-28',
                'height' => 188,
                'weight' => 82,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 450000,
                'bio' => 'Gardien international tunisien, pilier de la défense du CSS. Connu pour ses réflexes impressionnants et son leadership.',
                'statistics' => json_encode([
                    'matches_played' => 156,
                    'clean_sheets' => 67,
                    'goals_conceded' => 112,
                    'saves' => 421,
                    'penalties_saved' => 8
                ]),
            ],
            [
                'first_name' => 'Ali',
                'last_name' => 'Jemal',
                'position' => 'GK',
                'jersey_number' => 1,
                'nationality' => 'Tunisie',
                'birth_date' => '1999-05-12',
                'height' => 185,
                'weight' => 79,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 180000,
                'bio' => 'Jeune gardien prometteur, remplaçant de confiance.',
                'statistics' => json_encode([
                    'matches_played' => 34,
                    'clean_sheets' => 12,
                    'goals_conceded' => 29,
                    'saves' => 98,
                    'penalties_saved' => 2
                ]),
            ],
            [
                'first_name' => 'Mohamed',
                'last_name' => 'Sedki',
                'position' => 'GK',
                'jersey_number' => 30,
                'nationality' => 'Tunisie',
                'birth_date' => '2001-03-15',
                'height' => 183,
                'weight' => 76,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 120000,
                'bio' => 'Gardien espoir formé au club.',
                'statistics' => json_encode([
                    'matches_played' => 8,
                    'clean_sheets' => 2,
                    'goals_conceded' => 11,
                    'saves' => 23,
                    'penalties_saved' => 0
                ]),
            ],

            // Défenseurs (9)
            [
                'first_name' => 'Houssem',
                'last_name' => 'Dagdoug',
                'position' => 'DEF',
                'jersey_number' => 3,
                'nationality' => 'Tunisie',
                'birth_date' => '1996-08-20',
                'height' => 182,
                'weight' => 76,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 320000,
                'bio' => 'Défenseur latéral gauche dynamique, excellent dans les montées offensives.',
                'statistics' => json_encode([
                    'matches_played' => 142,
                    'goals' => 8,
                    'assists' => 15,
                    'minutes_played' => 11890,
                    'yellow_cards' => 23,
                    'red_cards' => 1
                ]),
            ],
            [
                'first_name' => 'Mohamed',
                'last_name' => 'Dhaoui',
                'position' => 'DEF',
                'jersey_number' => 4,
                'nationality' => 'Tunisie',
                'birth_date' => '1994-02-17',
                'height' => 187,
                'weight' => 82,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 280000,
                'bio' => 'Défenseur central robuste et expérimenté, leader de la défense.',
                'statistics' => json_encode([
                    'matches_played' => 178,
                    'goals' => 12,
                    'assists' => 5,
                    'minutes_played' => 15234,
                    'yellow_cards' => 34,
                    'red_cards' => 2
                ]),
            ],
            [
                'first_name' => 'Kingsley',
                'last_name' => 'Eduwo',
                'position' => 'DEF',
                'jersey_number' => 5,
                'nationality' => 'Nigeria',
                'birth_date' => '1995-06-10',
                'height' => 190,
                'weight' => 85,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 380000,
                'bio' => 'Défenseur central nigérian puissant, excellent dans les duels aériens.',
                'statistics' => json_encode([
                    'matches_played' => 89,
                    'goals' => 6,
                    'assists' => 3,
                    'minutes_played' => 7812,
                    'yellow_cards' => 18,
                    'red_cards' => 1
                ]),
            ],
            [
                'first_name' => 'Hamza',
                'last_name' => 'Jelassi',
                'position' => 'DEF',
                'jersey_number' => 2,
                'nationality' => 'Tunisie',
                'birth_date' => '1998-09-05',
                'height' => 179,
                'weight' => 73,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 250000,
                'bio' => 'Défenseur latéral droit rapide et technique.',
                'statistics' => json_encode([
                    'matches_played' => 98,
                    'goals' => 4,
                    'assists' => 12,
                    'minutes_played' => 8123,
                    'yellow_cards' => 15,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Rubin',
                'last_name' => 'Hebaj',
                'position' => 'DEF',
                'jersey_number' => 15,
                'nationality' => 'Kosovo',
                'birth_date' => '1997-04-22',
                'height' => 184,
                'weight' => 78,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 290000,
                'bio' => 'Défenseur polyvalent, peut jouer sur plusieurs postes.',
                'statistics' => json_encode([
                    'matches_played' => 67,
                    'goals' => 3,
                    'assists' => 7,
                    'minutes_played' => 5689,
                    'yellow_cards' => 12,
                    'red_cards' => 1
                ]),
            ],
            [
                'first_name' => 'Adem',
                'last_name' => 'Khalfa',
                'position' => 'DEF',
                'jersey_number' => 24,
                'nationality' => 'Tunisie',
                'birth_date' => '2000-07-18',
                'height' => 181,
                'weight' => 75,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 180000,
                'bio' => 'Jeune défenseur prometteur formé au club.',
                'statistics' => json_encode([
                    'matches_played' => 42,
                    'goals' => 1,
                    'assists' => 4,
                    'minutes_played' => 3234,
                    'yellow_cards' => 8,
                    'red_cards' => 0
                ]),
            ],

            // Milieux de terrain (10)
            [
                'first_name' => 'Firas',
                'last_name' => 'Chaouat',
                'position' => 'MID',
                'jersey_number' => 8,
                'nationality' => 'Tunisie',
                'birth_date' => '1995-03-11',
                'height' => 178,
                'weight' => 72,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 420000,
                'bio' => 'Milieu de terrain créatif et technique, maître à jouer de l\'équipe.',
                'statistics' => json_encode([
                    'matches_played' => 167,
                    'goals' => 28,
                    'assists' => 42,
                    'minutes_played' => 13456,
                    'yellow_cards' => 19,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Hazem',
                'last_name' => 'Haj Hassen',
                'position' => 'MID',
                'jersey_number' => 17,
                'nationality' => 'Tunisie',
                'birth_date' => '1996-11-08',
                'height' => 176,
                'weight' => 70,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 340000,
                'bio' => 'Milieu offensif rapide et technique.',
                'statistics' => json_encode([
                    'matches_played' => 134,
                    'goals' => 22,
                    'assists' => 31,
                    'minutes_played' => 10234,
                    'yellow_cards' => 14,
                    'red_cards' => 1
                ]),
            ],
            [
                'first_name' => 'Mohamed Ali',
                'last_name' => 'Ben Romdhane',
                'position' => 'MID',
                'jersey_number' => 10,
                'nationality' => 'Tunisie',
                'birth_date' => '2000-09-03',
                'height' => 173,
                'weight' => 68,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 500000,
                'bio' => 'Jeune talent international tunisien, milieu offensif très talentueux.',
                'statistics' => json_encode([
                    'matches_played' => 89,
                    'goals' => 18,
                    'assists' => 25,
                    'minutes_played' => 7123,
                    'yellow_cards' => 8,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Aymen',
                'last_name' => 'Abdennour',
                'position' => 'MID',
                'jersey_number' => 6,
                'nationality' => 'Tunisie',
                'birth_date' => '1997-12-25',
                'height' => 180,
                'weight' => 75,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 290000,
                'bio' => 'Milieu défensif solide, récupérateur de ballon.',
                'statistics' => json_encode([
                    'matches_played' => 112,
                    'goals' => 5,
                    'assists' => 9,
                    'minutes_played' => 9456,
                    'yellow_cards' => 28,
                    'red_cards' => 2
                ]),
            ],
            [
                'first_name' => 'Ghazi',
                'last_name' => 'Ayadi',
                'position' => 'MID',
                'jersey_number' => 18,
                'nationality' => 'Tunisie',
                'birth_date' => '1998-05-30',
                'height' => 177,
                'weight' => 71,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 260000,
                'bio' => 'Milieu polyvalent, capable de jouer sur plusieurs postes.',
                'statistics' => json_encode([
                    'matches_played' => 87,
                    'goals' => 11,
                    'assists' => 14,
                    'minutes_played' => 6789,
                    'yellow_cards' => 11,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Youssef',
                'last_name' => 'Becha',
                'position' => 'MID',
                'jersey_number' => 14,
                'nationality' => 'Tunisie',
                'birth_date' => '1999-08-14',
                'height' => 175,
                'weight' => 69,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 230000,
                'bio' => 'Milieu offensif créatif.',
                'statistics' => json_encode([
                    'matches_played' => 76,
                    'goals' => 9,
                    'assists' => 17,
                    'minutes_played' => 5234,
                    'yellow_cards' => 7,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Seif',
                'last_name' => 'Teka',
                'position' => 'MID',
                'jersey_number' => 20,
                'nationality' => 'Tunisie',
                'birth_date' => '2001-02-19',
                'height' => 172,
                'weight' => 67,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 190000,
                'bio' => 'Jeune milieu prometteur.',
                'statistics' => json_encode([
                    'matches_played' => 45,
                    'goals' => 6,
                    'assists' => 8,
                    'minutes_played' => 3123,
                    'yellow_cards' => 4,
                    'red_cards' => 0
                ]),
            ],

            // Attaquants (8)
            [
                'first_name' => 'Pedro',
                'last_name' => 'Sá',
                'position' => 'ATT',
                'jersey_number' => 9,
                'nationality' => 'Brésil',
                'birth_date' => '1995-07-14',
                'height' => 183,
                'weight' => 78,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 480000,
                'bio' => 'Attaquant brésilien prolifique, meilleur buteur de l\'équipe.',
                'statistics' => json_encode([
                    'matches_played' => 98,
                    'goals' => 56,
                    'assists' => 18,
                    'minutes_played' => 7890,
                    'yellow_cards' => 12,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Aymen',
                'last_name' => 'Harzi',
                'position' => 'ATT',
                'jersey_number' => 7,
                'nationality' => 'Tunisie',
                'birth_date' => '1997-01-23',
                'height' => 179,
                'weight' => 74,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 360000,
                'bio' => 'Ailier gauche rapide et dribbleur.',
                'statistics' => json_encode([
                    'matches_played' => 145,
                    'goals' => 38,
                    'assists' => 29,
                    'minutes_played' => 11234,
                    'yellow_cards' => 16,
                    'red_cards' => 1
                ]),
            ],
            [
                'first_name' => 'Kingsley',
                'last_name' => 'Sokari',
                'position' => 'ATT',
                'jersey_number' => 11,
                'nationality' => 'Nigeria',
                'birth_date' => '1996-04-08',
                'height' => 176,
                'weight' => 72,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 390000,
                'bio' => 'Ailier nigérian rapide et technique.',
                'statistics' => json_encode([
                    'matches_played' => 87,
                    'goals' => 29,
                    'assists' => 22,
                    'minutes_played' => 6789,
                    'yellow_cards' => 9,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Firas',
                'last_name' => 'Sekouhi',
                'position' => 'ATT',
                'jersey_number' => 19,
                'nationality' => 'Tunisie',
                'birth_date' => '1999-10-12',
                'height' => 174,
                'weight' => 70,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 270000,
                'bio' => 'Jeune attaquant prometteur.',
                'statistics' => json_encode([
                    'matches_played' => 67,
                    'goals' => 18,
                    'assists' => 11,
                    'minutes_played' => 4567,
                    'yellow_cards' => 5,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Iheb',
                'last_name' => 'Mbarki',
                'position' => 'ATT',
                'jersey_number' => 21,
                'nationality' => 'Tunisie',
                'birth_date' => '1998-06-27',
                'height' => 181,
                'weight' => 76,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 310000,
                'bio' => 'Attaquant puissant et opportuniste.',
                'statistics' => json_encode([
                    'matches_played' => 92,
                    'goals' => 24,
                    'assists' => 13,
                    'minutes_played' => 6234,
                    'yellow_cards' => 10,
                    'red_cards' => 1
                ]),
            ],
            [
                'first_name' => 'Zied',
                'last_name' => 'Aloui',
                'position' => 'ATT',
                'jersey_number' => 22,
                'nationality' => 'Tunisie',
                'birth_date' => '2000-11-05',
                'height' => 177,
                'weight' => 71,
                'contract_expires_at' => '2025-06-30',
                'market_value' => 220000,
                'bio' => 'Jeune ailier rapide.',
                'statistics' => json_encode([
                    'matches_played' => 54,
                    'goals' => 12,
                    'assists' => 9,
                    'minutes_played' => 3456,
                    'yellow_cards' => 6,
                    'red_cards' => 0
                ]),
            ],
            [
                'first_name' => 'Hamza',
                'last_name' => 'Agrebi',
                'position' => 'ATT',
                'jersey_number' => 27,
                'nationality' => 'Tunisie',
                'birth_date' => '2001-09-16',
                'height' => 175,
                'weight' => 69,
                'contract_expires_at' => '2026-06-30',
                'market_value' => 180000,
                'bio' => 'Espoir formé au club.',
                'statistics' => json_encode([
                    'matches_played' => 32,
                    'goals' => 8,
                    'assists' => 5,
                    'minutes_played' => 1876,
                    'yellow_cards' => 3,
                    'red_cards' => 0
                ]),
            ],
        ];

        foreach ($players as $player) {
            Player::create($player);
        }
    }
}
